pre-release-commit-message = "chore: Release gen-orb-mcp v{{version}}"
tag-message = "{{tag_name}}"
tag-name = "gen-orb-mcp-v{{version}}"
pre-release-hook = ["./release-hook.sh"]
pre-release-replacements = []
